modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Infinituum17/VoidLib/issues"
license = "MIT"

[[mods]]
modId = "void_lib"
version = "${version}"
displayName = "Void Lib"
authors = "Infinituum"
description = '''
A lib that adds various utilities to mod development
'''
logoFile = "assets/void_lib/icon.png"

[[dependencies.void_lib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.void_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.void_lib]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
