# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
java_version=21
# Mod properties
mod_version=1.1.6
maven_group=infinituum.void_lib
archives_name=void_lib
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.5
# Dependencies
fabric_loader_version=0.16.14
fabric_api_version=0.121.0+1.21.5
neoforge_version=21.5.63-beta
neoforge_loader_version=4
architectury_api_version=16.1.4
# Custom
has_generation=false