modLoader = "javafml"
loaderVersion = "[${loader_version},)"
issueTrackerURL = "https://github.com/Infinituum17/VoidLib/issues"
license = "Infinituum License"

[[mods]]
modId = "void_lib"
version = "${version}"
displayName = "Void Lib"
authors = "Infinituum"
description = '''
A lib that adds various utilities to mod development
'''
logoFile = "assets/void_lib/icon.png"

[[dependencies.void_lib]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_base_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.void_lib]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "void_lib-common.mixins.json"